package com.minesweeper;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

public class CoordinateTest extends TestCase {

    /**
     * Tests the getX and GetY method of the Coordinate class.
     * Makes sure the random x and y coordinates generated by the Coordinate class are within the proper boundaries.
     * The coordinates must have a value between 0 and 9.
     * @throws Exception
     */
    public void testCoordinateGetXY() throws Exception {
		Coordinate testCoordinate = new Coordinate();
        assertTrue("FAILURE: The generated x coordinate is either less than 0 or greater than 9. The value is: " + testCoordinate.getX(),
                ((testCoordinate.getX() >= 0) && (testCoordinate.getX() < 10)) );

        assertTrue("FAILURE: The generated y coordinate is either less than 0 or greater than 9. The value is: " + testCoordinate.getY(),
                ((testCoordinate.getY() >= 0) && (testCoordinate.getY() < 10)) );
    }

}
